language: cpp
sudo: false

matrix:
  include:

    # linux gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ['g++-5']
      env:
         - COMPILER='g++-5'

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ['g++-6']
      env:
        - COMPILER='g++-6'

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ['g++-7']
      env:
        - COMPILER='g++-7'

    # os X
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER='clang++'

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER='clang++'

    - os: osx
      osx_image: xcode9
      compiler: clang
      env: COMPILER='clang++'

    - os: osx
      osx_image: xcode10
      compiler: clang
      env: COMPILER='clang++'


addons:
  homebrew:
    packages:
    - lcov
    update: true
  apt:
    packages:
    - lcov
    update: true

before_install:
  - export CXX=${COMPILER}

install:
  - cmake .

script:
  - make
  - ./lua-format-test

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '*/usr/*' '*/test/*' '*/generated/*' '*/third_party/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"