osx_image: xcode8

language: cpp

os: 
  - osx

compiler:
  - gcc
  - clang

addons:
  homebrew:
    packages:
    - antlr4-cpp-runtime
    - lcov
    update: true

install:
  - cmake .

script:
  - make
  - make test

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' 'test/*' 'generated/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"