environment:
  matrix:
    - VisualStudioVersion: 14.0
      platform: "Win32"
      configuration: "Release"
      vcvarsall_platform: "x86"
      PlatformToolset: "v140"
    - VisualStudioVersion: 14.0
      platform: "Win32"
      configuration: "Debug"
      vcvarsall_platform: "x86"
      PlatformToolset: "v140"


before_build:
  - cmake . -G "Visual Studio 14"

build_script:
  - msbuild "lua-formatter.sln" /clp:ErrorsOnly /target:Build /property:Configuration="%configuration%";Platform=%platform% /p:PlatformToolset=%PlatformToolset% /m"

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\%configuration%
  - lua-format-test.exe

artifacts:
  - path: Release\lua-format.exe